import '@/app/globals.css';
import { PropsWithChildren } from 'react';

import type { Metadata, NextPage } from 'next';
import { Inter } from 'next/font/google';

import { ThemeProvider } from '@/components/theme/provider';
import { TopBar } from '@/components/top-bar';
import { Toaster } from '@/components/ui/toaster';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Pro Helper',
  description: 'Generated by create next app',
};

const RootLayout: NextPage<PropsWithChildren> = ({ children }) => (
  <html lang="pt-br">
    <body className={cn('bg-background font-sans antialiased', inter.variable)}>
      <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        disableTransitionOnChange
      >
        <main className="flex min-h-screen flex-col gap-4">
          <TopBar />
          {children}
        </main>
        <Toaster />
      </ThemeProvider>
    </body>
  </html>
);

export default RootLayout;
